spring.application.name=anubhav
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lms_db}
spring.datasource.username=${DB_USER:ad1tyq}
spring.datasource.password=${DB_PASS:m33tY0urP@dr}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
